### ISSUE TITLE
Add chain strategy

### ISSUE THREAD

**Issue by migo315** [bestit/flagception-sdk#13]
Two strategies for chaining activators:
- single: Just one of all chaining activators must return true for activate the feature
- all: All declared chaining activators must return true for activate the feature

**Comment by migo315** [comment]
Currently not planned

**Comment by danielsantiago** [comment]
Hi,

First, thanks for the library. I was looking for a way to do the "all" strategy in the chaining activator, do you think I should create another Activator or try to add the "strategy" option to the current one?

PS: I know I can create my own local activator extending the interface but I like the idea to contribute back to the project.

**Comment by migo315** [comment]
Hey @danielsantiago,

thanks for your help - contribution is welcome ;-)

I think we can add this to the current one. Maybe something like that?

```php
namespace Flagception\Activator;

use Flagception\Model\Context;

// At least one activator must return true to activating the feature (default)
const STRATEGY_FIRST_MATCH = 1;

// All activators must return true to activating the feature
const STRATEGY_ALL_MATCH = 2;

class ChainActivator implements FeatureActivatorInterface
{
   public function __construct(int $strategy = self::STRATEGY_FIRST_MATCH) 
   {
      // ...
   }
}
```

This implementation wouldn't be a breaking change and we have the chance to add new strategies in future. What dou you think?

**Comment by migo315** [comment]
Merged into master
