### ISSUE TITLE
Dont rely on PHP globals for cookies

### ISSUE THREAD

**Issue by Haehnchen** [bestit/flagception-sdk#19]
For activating cookies there is a directy access to `$_COOKIE`, for now its not suitable to use together with the Symfony bundle.

You should move this loading into a interface and maybe provide here just an implementation via globals. The Symfony bundle should then use a RequestStack implementation.

```php
return in_array($name, array_map('trim', explode($this->separator, $_COOKIE[$this->name])), true);
```

**Comment by migo315** [comment]
Thanks for the hint @Haehnchen. I will check it ...

**Comment by migo315** [comment]
Merged into master.

**Comment by migo315** [comment]
A PR for Bundle will be created shortly.
