### ISSUE TITLE
Flagception is not compatible with PHP 8.1

### ISSUE THREAD

**Issue by dkreuer** [bestit/flagception-sdk#29]
Hello there!

Since PHP 8.1.0 is released it would be great if the library would be compatible with it as well.

I guess first steps would be to extend travis-ci and composer requirements - given that travis-ci still works (which I assume it does not!).
Otherwise how about switching to github actions?

Do you need help doing that? I'd be happy to volunteer.

**Comment by winkbrace** [comment]
This deprecation can also be addressed:

As of PHP 8.1.0, a class which implements Serializable without also implementing [__serialize()](https://www.php.net/manual/en/language.oop5.magic.php#object.serialize) and [__unserialize()](https://www.php.net/manual/en/language.oop5.magic.php#object.unserialize) will generate a deprecation warning.

Edit: I see there is already a PR for this. Please merge it?

**Comment by mKnoop** [comment]
We have released a new version 1.8.0.  The SDK should now be compatible with Symfony 6.0 and PHP 8.1. 

If you encounter problems with the PHP 8.1 in the context of this release, please create a new issue.
