### ISSUE TITLE
Maintenance handover for bestit/flagception-bundle

### ISSUE THREAD

**Issue by yakobe** [bestit/flagception-sdk#40]
Hello BestIT Team

The https://github.com/bestit/flagception-bundle has been archived without allowing a discussion about who will take it over. There was a discussion on https://github.com/bestit/flagception-bundle/issues/106 about the status, and it would be good if the conversation was concluded with an official handover to a new maintainer. As it stands now, there is no clear repository to use as a replacement and packagist shows ` This package is abandoned and no longer maintained. No replacement package was suggested. `

Would it be possible to allow a graceful handover, since many people still use it and the bundle is actively promoted through many symfony blogs? @javiereguiluz the recent https://symfony.com/blog/a-week-of-symfony-869-21-27-august-2023 has a [link](https://medium.com/@skowron.jakub1/unlock-the-power-of-dynamic-features-in-symfony-the-ultimate-guide-to-implement-feature-flags-88b9e5e41085) by @JakubSkowron to suggest this bundle. It's a great bundle and it would be really nice if we could keep it going 🙂 

I think https://github.com/hanishsingla has started a fork. Perhaps he is willing to take over and packagist could suggest it as a replacement? Or maybe someone else?

**Comment by teiling88** [comment]
Hey @yakobe,
@migo315 (the former maintainer) and I are wiling to maintain this package under the hood of https://github.com/playox. 
but we need the access to the packagist name for a smooth update path. 
Greetings,
Thomas

**Comment by teiling88** [comment]
First PR is merged and the ci process is switched from travis to github actions. We already created some issues. If there is an issue missing, please add it there https://github.com/playox/flagception-bundle/issues

**Comment by yakobe** [comment]
@teiling88 great stuff! And thank you for the proactive adoption of the bundle. Now we just need to work out how we can get packagist to link it over. 

@mika350 is there any chance of you being able to give access to @teiling88 to make the necessary changes? Or to mark the new location as the replacement?

**Comment by mika350** [comment]
@yakobe 
I talked with @migo315 about this. He moved the package into the namespace of playox (https://github.com/playox/flagception-bundle). Everything should be fine now.

**Comment by teiling88** [comment]
Hey @mika350 
thank you for your fast response. We have now access to the flageception namespace on packagist. 

We contacted the owner of packagist for the new url of the flageception repository. After that, we can publish the new version from there new home. 

@yakobe if you have some issue etc. please add them on the playox repo.

**Comment by teiling88** [comment]
Everything moved to github.com/playox the packagist entries will remain - no update needed :-)

**Comment by yakobe** [comment]
This is all great news! Thanks everyone. I will get into the issues and will also try to help where I can.
